In [1]:
import numpy as np
import pandas as pd

### 2.1 選取多個DataFrame 欄位

In [2]:
# 取出多個欄位
movies = pd.read_csv('../../data/movie.csv')
movie_actor_director = movies[['actor_1_name','actor_2_name','actor_3_name',
                               'director_name']]
movie_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

In [3]:
# 選取單一欄位但回傳DataFrame
print(type(movies[['director_name']]))
print(type(movies['director_name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [4]:
# 使用loc屬性選取多個欄位
print(type(movies.loc[:, ['director_name']]))
print(type(movies.loc[:, 'director_name']))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [6]:
# 長的串列 先指派變數
cols = ['actor_1_name','actor_2_name','actor_3_name','director_name']
movie_actor_director = movies[cols]
movie_actor_director

,actor_1_name,actor_2_name,actor_3_name,director_name
0,CCH Pounder,Joel David Moore,Wes Studi,James Cameron
1,Johnny Depp,Orlando Bloom,Jack Davenport,Gore Verbinski
2,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Sam Mendes
3,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Christopher Nolan
4,Doug Walker,Rob Walker,NaN,Doug Walker
...,...,...,...,...
4911,Eric Mabius,Daphne Zuniga,Crystal Lowe,Scott Smith
4912,Natalie Zea,Valorie Curry,Sam Underwood,NaN
4913,Eva Boehnke,Maxwell Moody,David Chandler,Benjamin Roberds
4914,Alan Ruck,Daniel Henney,Eliza Coupe,Daniel Hsia
4915,John August,Brian Herzlinger,Jon Gunn,Jon Gunn

In [7]:
# 忘了用串列 指定多欄位
movies['actor_1_name','actor_2_name','actor_3_name','director_name']

KeyError: ('actor_1_name', 'actor_2_name', 'actor_3_name', 'director_name')

### 2.2 用方法選取欄位

In [8]:
# 查看dtypes
movies.dtypes.value_counts()

float64    13
object     12
int64       3
Name: count, dtype: int64

In [9]:
# 選取特定dtype
movies.select_dtypes(include='object')

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,Daphne Zuniga,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,Crystal Lowe,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,English,Canada,NaN
4912,Color,NaN,Valorie Curry,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,Sam Underwood,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,English,USA,TV-14
4913,Color,Benjamin Roberds,Maxwell Moody,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,David Chandler,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,English,USA,NaN
4914,Color,Daniel Hsia,Daniel Henney,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,Eliza Coupe,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,English,USA,PG-13
4915,Color,Jon Gunn,Brian Herzlinger,Documentary,John August,My Date with Drew,Jon Gunn,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,English,USA,PG

In [15]:
# number 參數 可以一次回傳 int 與float
def shorten(col):
    return (col.replace('facebook_likes', 'fb')
                .replace('_for_reviews', ''))
movies = movies.rename(columns=shorten)
movies.select_dtypes(include='number').head()

,num_critic,duration,director_fb,actor_3_fb,actor_1_fb,gross,num_voted_users,cast_total_fb,facenumber_in_poster,num_user,budget,title_year,actor_2_fb,imdb_score,aspect_ratio,movie_fb
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0

In [18]:
# 用字串選取兩種型別
movies.select_dtypes(include=['int', 'object']).head()

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,num_voted_users,cast_total_fb,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating,movie_fb
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13,33000
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13,0
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13,85000
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13,164000
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,0

In [24]:
# exclude
movies.select_dtypes(exclude='float').head()

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,num_voted_users,cast_total_fb,actor_3_name,plot_keywords,movie_imdb_link,language,country,content_rating,movie_fb
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,USA,PG-13,33000
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,USA,PG-13,0
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,UK,PG-13,85000
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,USA,PG-13,164000
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,8,143,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,0

In [20]:
# like
movies.filter(like='fb').head()

   director_fb  actor_3_fb  actor_1_fb  cast_total_fb  actor_2_fb  movie_fb
0          0.0       855.0      1000.0           4834       936.0     33000
1        563.0      1000.0     40000.0          48350      5000.0         0
2          0.0       161.0     11000.0          11700       393.0     85000
3      22000.0     23000.0     27000.0         106759     23000.0    164000
4        131.0         NaN       131.0            143        12.0         0

In [21]:
# item
cols = ['actor_1_name', 'actor_2_name', 'actor_3_name', 'direcotr']
movies.filter(items=cols).head()

      actor_1_name      actor_2_name          actor_3_name
0      CCH Pounder  Joel David Moore             Wes Studi
1      Johnny Depp     Orlando Bloom        Jack Davenport
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt
4      Doug Walker        Rob Walker                   NaN

In [22]:
# regex
movies.filter(regex=r'\d').head()

,actor_3_fb,actor_2_name,actor_1_fb,actor_1_name,actor_3_name,actor_2_fb
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

### 2.3 對欄位名稱進行排序